'use client';

import { useState, useEffect, useRef } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { Upload, Palette, FileText, Building2, X, Check, Image as ImageIcon } from 'lucide-react';
import Image from 'next/image';
import { secondaryColors, semanticColors } from '@/lib/design-tokens';

interface ExportSettings {
  companyName: string;
  companyLogo: string;
  primaryColor: string;
  secondaryColor: string;
  headerText: string;
  footerText: string;
  showWeekends: boolean;
  showLegend: boolean;
  showSummary: boolean;
}

interface ExportSettingsModalProps {
  open: boolean;
  onClose: () => void;
  projectSlug: string;
  onSettingsSaved?: () => void;
}

const defaultSettings: ExportSettings = {
  companyName: '',
  companyLogo: '',
  primaryColor: secondaryColors.blue.brand,
  secondaryColor: semanticColors.success[500],
  headerText: '3-Week Lookahead Schedule',
  footerText: 'Generated by ForemanOS',
  showWeekends: true,
  showLegend: true,
  showSummary: true,
};

export default function ExportSettingsModal({ 
  open, 
  onClose, 
  projectSlug,
  onSettingsSaved 
}: ExportSettingsModalProps) {
  const [settings, setSettings] = useState<ExportSettings>(defaultSettings);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [uploading, setUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      fetchSettings();
    }
  }, [open, projectSlug]);

  const fetchSettings = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/projects/${projectSlug}/export-settings`);
      if (response.ok) {
        const data = await response.json();
        if (data.settings) {
          setSettings({ ...defaultSettings, ...data.settings });
        }
      }
    } catch (error) {
      console.error('Error fetching export settings:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    try {
      setSaving(true);
      const response = await fetch(`/api/projects/${projectSlug}/export-settings`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ settings }),
      });

      if (!response.ok) throw new Error('Failed to save settings');

      toast.success('Export settings saved');
      onSettingsSaved?.();
      onClose();
    } catch (error) {
      console.error('Error saving settings:', error);
      toast.error('Failed to save settings');
    } finally {
      setSaving(false);
    }
  };

  const handleLogoUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('Please upload an image file');
      return;
    }

    // Validate file size (max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      toast.error('Image must be less than 2MB');
      return;
    }

    try {
      setUploading(true);

      // Get presigned URL
      const presignedResponse = await fetch('/api/upload/presigned', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fileName: file.name,
          contentType: file.type,
          isPublic: true,
        }),
      });

      if (!presignedResponse.ok) throw new Error('Failed to get upload URL');
      const { uploadUrl, cloud_storage_path } = await presignedResponse.json();

      // Check if we need to include Content-Disposition header
      const signedHeadersMatch = uploadUrl.match(/X-Amz-SignedHeaders=([^&]+)/);
      const signedHeaders = signedHeadersMatch ? decodeURIComponent(signedHeadersMatch[1]) : '';
      const needsContentDisposition = signedHeaders.includes('content-disposition');

      // Upload to S3
      const uploadHeaders: Record<string, string> = {
        'Content-Type': file.type,
      };
      if (needsContentDisposition) {
        uploadHeaders['Content-Disposition'] = 'attachment';
      }

      const uploadResponse = await fetch(uploadUrl, {
        method: 'PUT',
        headers: uploadHeaders,
        body: file,
      });

      if (!uploadResponse.ok) throw new Error('Failed to upload file');

      // Complete upload
      const completeResponse = await fetch('/api/upload/complete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cloud_storage_path, isPublic: true }),
      });

      if (!completeResponse.ok) throw new Error('Failed to complete upload');
      const { url } = await completeResponse.json();

      setSettings(prev => ({ ...prev, companyLogo: url }));
      toast.success('Logo uploaded successfully');
    } catch (error) {
      console.error('Error uploading logo:', error);
      toast.error('Failed to upload logo');
    } finally {
      setUploading(false);
      if (fileInputRef.current) {
        fileInputRef.current.value = '';
      }
    }
  };

  const removeLogo = () => {
    setSettings(prev => ({ ...prev, companyLogo: '' }));
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl bg-dark-subtle border-gray-700 text-white">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <FileText className="h-5 w-5 text-orange-400" aria-hidden="true" />
            Export Customization
          </DialogTitle>
        </DialogHeader>

        {loading ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-orange-500"></div>
          </div>
        ) : (
          <div className="space-y-6 py-4">
            {/* Company Branding Section */}
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                <Building2 className="h-4 w-4" aria-hidden="true" />
                Company Branding
              </h3>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="companyName" className="text-gray-400">Company Name</Label>
                  <Input
                    id="companyName"
                    value={settings.companyName}
                    onChange={e => setSettings(prev => ({ ...prev, companyName: e.target.value }))}
                    placeholder="Your Company Name"
                    className="bg-dark-base border-gray-700 text-white"
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-gray-400">Company Logo</Label>
                  <div className="flex items-center gap-2">
                    {settings.companyLogo ? (
                      <div className="relative h-10 w-32 bg-gray-800 rounded border border-gray-700 overflow-hidden">
                        <Image
                          src={settings.companyLogo}
                          alt="Company Logo"
                          fill
                          className="object-contain p-1"
                        />
                        <button
                          onClick={removeLogo}
                          className="absolute top-0 right-0 p-0.5 bg-red-500/80 rounded-bl hover:bg-red-600"
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </div>
                    ) : (
                      <div className="h-10 w-32 bg-gray-800 rounded border border-dashed border-gray-600 flex items-center justify-center">
                        <ImageIcon className="h-4 w-4 text-gray-400" aria-hidden="true" />
                      </div>
                    )}
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={uploading}
                      className="border-gray-600 hover:bg-gray-700"
                    >
                      {uploading ? (
                        <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
                      ) : (
                        <><Upload className="h-4 w-4 mr-1" aria-hidden="true" /> Upload</>
                      )}
                    </Button>
                    <input
                      ref={fileInputRef}
                      type="file"
                      accept="image/*"
                      onChange={handleLogoUpload}
                      className="hidden"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Colors Section */}
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                <Palette className="h-4 w-4" aria-hidden="true" />
                Colors
              </h3>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="primaryColor" className="text-gray-400">Primary Color</Label>
                  <div className="flex items-center gap-2">
                    <input
                      type="color"
                      id="primaryColor"
                      value={settings.primaryColor}
                      onChange={e => setSettings(prev => ({ ...prev, primaryColor: e.target.value }))}
                      className="h-10 w-14 rounded border border-gray-700 cursor-pointer"
                    />
                    <Input
                      value={settings.primaryColor}
                      onChange={e => setSettings(prev => ({ ...prev, primaryColor: e.target.value }))}
                      className="bg-dark-base border-gray-700 text-white font-mono"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="secondaryColor" className="text-gray-400">Secondary Color</Label>
                  <div className="flex items-center gap-2">
                    <input
                      type="color"
                      id="secondaryColor"
                      value={settings.secondaryColor}
                      onChange={e => setSettings(prev => ({ ...prev, secondaryColor: e.target.value }))}
                      className="h-10 w-14 rounded border border-gray-700 cursor-pointer"
                    />
                    <Input
                      value={settings.secondaryColor}
                      onChange={e => setSettings(prev => ({ ...prev, secondaryColor: e.target.value }))}
                      className="bg-dark-base border-gray-700 text-white font-mono"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Text Customization */}
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-gray-300 flex items-center gap-2">
                <FileText className="h-4 w-4" aria-hidden="true" />
                Text Customization
              </h3>
              
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="headerText" className="text-gray-400">Header Title</Label>
                  <Input
                    id="headerText"
                    value={settings.headerText}
                    onChange={e => setSettings(prev => ({ ...prev, headerText: e.target.value }))}
                    placeholder="3-Week Lookahead Schedule"
                    className="bg-dark-base border-gray-700 text-white"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="footerText" className="text-gray-400">Footer Text</Label>
                  <Input
                    id="footerText"
                    value={settings.footerText}
                    onChange={e => setSettings(prev => ({ ...prev, footerText: e.target.value }))}
                    placeholder="Generated by ForemanOS"
                    className="bg-dark-base border-gray-700 text-white"
                  />
                </div>
              </div>
            </div>

            {/* Display Options */}
            <div className="space-y-4">
              <h3 className="text-sm font-semibold text-gray-300">Display Options</h3>
              
              <div className="flex flex-wrap gap-4">
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={settings.showWeekends}
                    onChange={e => setSettings(prev => ({ ...prev, showWeekends: e.target.checked }))}
                    className="rounded border-gray-600 bg-gray-800 text-orange-500 focus:ring-orange-500"
                  />
                  <span className="text-sm text-gray-300">Highlight Weekends</span>
                </label>

                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={settings.showLegend}
                    onChange={e => setSettings(prev => ({ ...prev, showLegend: e.target.checked }))}
                    className="rounded border-gray-600 bg-gray-800 text-orange-500 focus:ring-orange-500"
                  />
                  <span className="text-sm text-gray-300">Show Legend</span>
                </label>

                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={settings.showSummary}
                    onChange={e => setSettings(prev => ({ ...prev, showSummary: e.target.checked }))}
                    className="rounded border-gray-600 bg-gray-800 text-orange-500 focus:ring-orange-500"
                  />
                  <span className="text-sm text-gray-300">Show Summary Statistics</span>
                </label>
              </div>
            </div>

            {/* Preview */}
            <div className="p-4 bg-white rounded-lg">
              <div className="flex items-center gap-3 border-b pb-3 mb-3" style={{ borderColor: settings.primaryColor }}>
                {settings.companyLogo && (
                  <div className="relative h-8 w-24">
                    <Image src={settings.companyLogo} alt="Logo" fill className="object-contain" />
                  </div>
                )}
                <div>
                  <h4 className="font-bold" style={{ color: settings.primaryColor }}>{settings.headerText || '3-Week Lookahead Schedule'}</h4>
                  {settings.companyName && <p className="text-xs text-gray-600">{settings.companyName}</p>}
                </div>
              </div>
              <div className="flex gap-2">
                <div className="h-4 w-16 rounded" style={{ backgroundColor: settings.primaryColor }}></div>
                <div className="h-4 w-12 rounded" style={{ backgroundColor: settings.secondaryColor }}></div>
                <div className="h-4 w-20 rounded bg-gray-300"></div>
              </div>
              <p className="text-xs text-gray-400 mt-3 text-center">{settings.footerText}</p>
            </div>
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={onClose} className="border-gray-600 hover:bg-gray-700">
            Cancel
          </Button>
          <Button
            onClick={handleSave}
            disabled={saving}
            className="bg-orange-500 hover:bg-orange-600"
          >
            {saving ? (
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white" />
            ) : (
              <><Check className="h-4 w-4 mr-1" aria-hidden="true" /> Save Settings</>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
