import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/db';
import { format, eachDayOfInterval, differenceInDays, startOfDay, isWeekend, getDay } from 'date-fns';

export const dynamic = 'force-dynamic';

interface ExportSettings {
  companyName?: string;
  companyLogo?: string;
  primaryColor?: string;
  secondaryColor?: string;
  headerText?: string;
  footerText?: string;
  showWeekends?: boolean;
  showLegend?: boolean;
  showSummary?: boolean;
}

const defaultSettings: ExportSettings = {
  companyName: '',
  companyLogo: '',
  primaryColor: '#003B71',
  secondaryColor: '#10B981',
  headerText: '3-Week Lookahead Schedule',
  footerText: 'Generated by ForemanOS',
  showWeekends: true,
  showLegend: true,
  showSummary: true,
};

function getStatusColor(status: string): { bg: string; border: string; text: string } {
  switch (status) {
    case 'completed':
      return { bg: '#10B981', border: '#059669', text: '#ffffff' };
    case 'in_progress':
      return { bg: '#3B82F6', border: '#2563EB', text: '#ffffff' };
    case 'delayed':
      return { bg: '#EF4444', border: '#DC2626', text: '#ffffff' };
    case 'on_hold':
      return { bg: '#F59E0B', border: '#D97706', text: '#ffffff' };
    default:
      return { bg: '#6B7280', border: '#4B5563', text: '#ffffff' };
  }
}

function formatStatusLabel(status: string): string {
  return status.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
}

export async function GET(req: NextRequest, { params }: { params: { slug: string } }) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { slug } = params;
    const { searchParams } = new URL(req.url);
    const startParam = searchParams.get('start');
    const endParam = searchParams.get('end');

    const startDate = startParam ? startOfDay(new Date(startParam)) : startOfDay(new Date());
    const endDate = endParam ? startOfDay(new Date(endParam)) : startOfDay(new Date(Date.now() + 21 * 24 * 60 * 60 * 1000));

    // Get project with tasks and export settings
    const project = await prisma.project.findUnique({
      where: { slug },
      include: {
        Schedule: {
          include: {
            ScheduleTask: {
              where: {
                OR: [
                  {
                    startDate: {
                      gte: startDate,
                      lte: endDate
                    }
                  },
                  {
                    endDate: {
                      gte: startDate,
                      lte: endDate
                    }
                  }
                ]
              },
              orderBy: { startDate: 'asc' }
            }
          }
        },
        ProjectMember: {
          include: {
            User: {
              select: {
                username: true
              }
            }
          }
        }
      }
    });

    // Merge export settings with defaults
    const exportSettings: ExportSettings = {
      ...defaultSettings,
      ...(project?.exportSettings as ExportSettings || {}),
    };

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const allTasks = (project as any).Schedule.flatMap((s: any) => s.ScheduleTask);

    // Generate all days in the range
    const allDays = eachDayOfInterval({ start: startDate, end: endDate });
    const totalDays = allDays.length;

    // Calculate day column width (in pixels)
    const dayWidth = 35;
    const taskLabelWidth = 280;
    const totalWidth = taskLabelWidth + (totalDays * dayWidth);

    // Group days by week
    const weeks: { start: Date; end: Date; days: Date[] }[] = [];
    let currentWeek: Date[] = [];
    let weekStart = allDays[0];
    
    allDays.forEach((day, index) => {
      currentWeek.push(day);
      // Week ends on Saturday or last day
      if (getDay(day) === 6 || index === allDays.length - 1) {
        weeks.push({
          start: weekStart,
          end: day,
          days: [...currentWeek]
        });
        currentWeek = [];
        if (index < allDays.length - 1) {
          weekStart = allDays[index + 1];
        }
      }
    });

    // Generate HTML Gantt chart with custom branding
    const primaryColor = exportSettings.primaryColor || '#003B71';
    const secondaryColor = exportSettings.secondaryColor || '#10B981';
    const headerText = exportSettings.headerText || '3-Week Lookahead Schedule';
    const footerText = exportSettings.footerText || 'Generated by ForemanOS';
    const companyName = exportSettings.companyName || '';
    const companyLogo = exportSettings.companyLogo || '';
    const showWeekends = exportSettings.showWeekends !== false;
    const showLegend = exportSettings.showLegend !== false;
    const showSummary = exportSettings.showSummary !== false;

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${headerText} - ${project.name}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: #ffffff;
      color: #1f2937;
      padding: 20px;
    }
    .header {
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 2px solid ${primaryColor};
      display: flex;
      align-items: center;
      gap: 16px;
    }
    .header-logo {
      max-height: 48px;
      max-width: 180px;
      object-fit: contain;
    }
    .header-content {
      flex: 1;
    }
    .header h1 {
      font-size: 24px;
      font-weight: 700;
      color: ${primaryColor};
      margin-bottom: 4px;
    }
    .header .company-name {
      font-size: 12px;
      color: #6b7280;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .header .subtitle {
      font-size: 14px;
      color: #6b7280;
    }
    .header .date-range {
      font-size: 16px;
      color: #374151;
      font-weight: 500;
      margin-top: 4px;
    }
    .gantt-container {
      overflow-x: auto;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      background: #fff;
    }
    .gantt {
      min-width: ${totalWidth}px;
    }
    .gantt-header {
      display: flex;
      background: #f9fafb;
      border-bottom: 2px solid #e5e7eb;
      position: sticky;
      top: 0;
      z-index: 10;
    }
    .gantt-header-task {
      width: ${taskLabelWidth}px;
      min-width: ${taskLabelWidth}px;
      padding: 12px 16px;
      font-weight: 600;
      font-size: 13px;
      color: #374151;
      border-right: 1px solid #e5e7eb;
      background: #f3f4f6;
    }
    .gantt-header-timeline {
      flex: 1;
      display: flex;
      flex-direction: column;
    }
    .week-row {
      display: flex;
      border-bottom: 1px solid #e5e7eb;
    }
    .week-header {
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 600;
      font-size: 12px;
      color: ${primaryColor};
      background: #f0f7ff;
      padding: 6px 0;
      border-right: 1px solid #d1d5db;
    }
    .day-row {
      display: flex;
    }
    .day-header {
      width: ${dayWidth}px;
      min-width: ${dayWidth}px;
      text-align: center;
      font-size: 10px;
      padding: 4px 2px;
      border-right: 1px solid #e5e7eb;
      background: #f9fafb;
    }
    .day-header.weekend {
      background: #fef3c7;
    }
    .day-header .day-name {
      font-weight: 600;
      color: #6b7280;
    }
    .day-header .day-num {
      font-weight: 700;
      color: #374151;
    }
    .gantt-body {
      display: flex;
      flex-direction: column;
    }
    .gantt-row {
      display: flex;
      border-bottom: 1px solid #e5e7eb;
      min-height: 48px;
    }
    .gantt-row:hover {
      background: #f9fafb;
    }
    .task-label {
      width: ${taskLabelWidth}px;
      min-width: ${taskLabelWidth}px;
      padding: 8px 12px;
      border-right: 1px solid #e5e7eb;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }
    .task-name {
      font-weight: 600;
      font-size: 13px;
      color: #1f2937;
      margin-bottom: 2px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .task-meta {
      font-size: 11px;
      color: #6b7280;
    }
    .task-timeline {
      flex: 1;
      display: flex;
      position: relative;
      align-items: center;
    }
    .day-cell {
      width: ${dayWidth}px;
      min-width: ${dayWidth}px;
      height: 100%;
      border-right: 1px solid #f3f4f6;
    }
    .day-cell.weekend {
      background: #fffbeb;
    }
    .task-bar {
      position: absolute;
      height: 28px;
      border-radius: 4px;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 10px;
      font-weight: 600;
      color: #fff;
      box-shadow: 0 1px 3px rgba(0,0,0,0.2);
      overflow: hidden;
      white-space: nowrap;
      text-overflow: ellipsis;
      padding: 0 8px;
      z-index: 5;
    }
    .legend {
      margin-top: 20px;
      padding: 16px;
      background: #f9fafb;
      border-radius: 8px;
      display: flex;
      flex-wrap: wrap;
      gap: 16px;
    }
    .legend-item {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 12px;
      color: #374151;
    }
    .legend-color {
      width: 20px;
      height: 14px;
      border-radius: 3px;
    }
    .summary {
      margin-top: 20px;
      padding: 16px;
      background: #f0f7ff;
      border-radius: 8px;
      border: 1px solid #bfdbfe;
    }
    .summary h3 {
      font-size: 14px;
      font-weight: 600;
      color: ${primaryColor};
      margin-bottom: 12px;
    }
    .summary-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
      gap: 12px;
    }
    .summary-item {
      background: #fff;
      padding: 12px;
      border-radius: 6px;
      text-align: center;
    }
    .summary-value {
      font-size: 24px;
      font-weight: 700;
      color: ${primaryColor};
    }
    .summary-label {
      font-size: 11px;
      color: #6b7280;
      margin-top: 4px;
    }
    .footer {
      margin-top: 24px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-size: 11px;
      color: #9ca3af;
      text-align: center;
    }
    @media print {
      body { padding: 10px; }
      .gantt-container { border: none; }
      .task-bar { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
      .legend-color { print-color-adjust: exact; -webkit-print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div class="header">
    ${companyLogo ? `<img src="${companyLogo}" alt="Company Logo" class="header-logo" />` : ''}
    <div class="header-content">
      ${companyName ? `<div class="company-name">${companyName}</div>` : ''}
      <h1>${headerText}</h1>
      <div class="subtitle">${project.name}</div>
      <div class="date-range">${format(startDate, 'MMMM d, yyyy')} — ${format(endDate, 'MMMM d, yyyy')}</div>
    </div>
  </div>

  <div class="gantt-container">
    <div class="gantt">
      <div class="gantt-header">
        <div class="gantt-header-task">Task / Activity</div>
        <div class="gantt-header-timeline">
          <div class="week-row">
            ${weeks.map(week => `
              <div class="week-header" style="width: ${week.days.length * dayWidth}px; min-width: ${week.days.length * dayWidth}px;">
                Week of ${format(week.start, 'MMM d')}
              </div>
            `).join('')}
          </div>
          <div class="day-row">
            ${allDays.map(day => `
              <div class="day-header ${showWeekends && isWeekend(day) ? 'weekend' : ''}">
                <div class="day-name">${format(day, 'EEE')}</div>
                <div class="day-num">${format(day, 'd')}</div>
              </div>
            `).join('')}
          </div>
        </div>
      </div>

      <div class="gantt-body">
        ${allTasks.length === 0 ? `
          <div class="gantt-row">
            <div class="task-label" style="width: 100%;">
              <div class="task-name" style="color: #6b7280; text-align: center;">No tasks scheduled for this period</div>
            </div>
          </div>
        ` : allTasks.map((task: any) => {
          const taskStart = startOfDay(new Date(task.startDate));
          const taskEnd = startOfDay(new Date(task.endDate));
          const duration = differenceInDays(taskEnd, taskStart) + 1;
          
          // Calculate bar position
          const startOffset = Math.max(0, differenceInDays(taskStart, startDate));
          const barLeft = startOffset * dayWidth;
          
          // Calculate bar width (clipped to visible range)
          const visibleStart = taskStart < startDate ? startDate : taskStart;
          const visibleEnd = taskEnd > endDate ? endDate : taskEnd;
          const visibleDuration = differenceInDays(visibleEnd, visibleStart) + 1;
          const barWidth = Math.max(visibleDuration * dayWidth - 4, dayWidth - 4);
          
          const colors = getStatusColor(task.status);
          const assignedMember = (project as any).ProjectMember.find((m: any) => m.userId === task.assignedTo);
          const assignedName = assignedMember?.User.username || 'Unassigned';
          
          return `
            <div class="gantt-row">
              <div class="task-label">
                <div class="task-name" title="${task.name}">${task.name}</div>
                <div class="task-meta">${format(taskStart, 'MMM d')} - ${format(taskEnd, 'MMM d')} · ${duration}d · ${assignedName}</div>
              </div>
              <div class="task-timeline">
                ${allDays.map(day => `<div class="day-cell ${showWeekends && isWeekend(day) ? 'weekend' : ''}"></div>`).join('')}
                <div class="task-bar" style="left: ${barLeft + 2}px; width: ${barWidth}px; background: ${colors.bg}; border: 1px solid ${colors.border};">
                  ${formatStatusLabel(task.status)}
                </div>
              </div>
            </div>
          `;
        }).join('')}
      </div>
    </div>
  </div>

  ${showLegend ? `
  <div class="legend">
    <div class="legend-item">
      <div class="legend-color" style="background: #10B981;"></div>
      <span>Completed</span>
    </div>
    <div class="legend-item">
      <div class="legend-color" style="background: #3B82F6;"></div>
      <span>In Progress</span>
    </div>
    <div class="legend-item">
      <div class="legend-color" style="background: #6B7280;"></div>
      <span>Not Started</span>
    </div>
    <div class="legend-item">
      <div class="legend-color" style="background: #EF4444;"></div>
      <span>Delayed</span>
    </div>
    <div class="legend-item">
      <div class="legend-color" style="background: #F59E0B;"></div>
      <span>On Hold</span>
    </div>
    ${showWeekends ? `
    <div class="legend-item" style="margin-left: auto;">
      <div style="width: 20px; height: 14px; background: #fffbeb; border: 1px solid #fde68a; border-radius: 3px;"></div>
      <span>Weekend</span>
    </div>
    ` : ''}
  </div>
  ` : ''}

  ${showSummary ? `
  <div class="summary">
    <h3>Schedule Summary</h3>
    <div class="summary-grid">
      <div class="summary-item">
        <div class="summary-value">${allTasks.length}</div>
        <div class="summary-label">Total Tasks</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${allTasks.filter((t: any) => t.status === 'completed').length}</div>
        <div class="summary-label">Completed</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${allTasks.filter((t: any) => t.status === 'in_progress').length}</div>
        <div class="summary-label">In Progress</div>
      </div>
      <div class="summary-item">
        <div class="summary-value">${allTasks.filter((t: any) => t.status === 'delayed').length}</div>
        <div class="summary-label">Delayed</div>
      </div>
    </div>
  </div>
  ` : ''}

  <div class="footer">
    ${footerText} · ${format(new Date(), 'MMMM d, yyyy \'at\' h:mm a')}
  </div>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="3-week-lookahead-${slug}-${format(startDate, 'yyyy-MM-dd')}.html"`
      }
    });

  } catch (error) {
    console.error('Error exporting lookahead:', error);
    return NextResponse.json(
      { error: 'Failed to export lookahead' },
      { status: 500 }
    );
  }
}