/**
 * Photos Export API for Daily Reports
 * 
 * GET /api/conversations/[id]/photos-export
 * Returns photo metadata and signed URLs for PDF generation
 */

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/db';
import { createS3Client, getBucketConfig } from '@/lib/aws-config';
import { GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { PhotoMetadata } from '@/lib/photo-analyzer';
import { createLogger } from '@/lib/logger';
const logger = createLogger('CONVERSATIONS_PHOTOS_EXPORT');

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest, props: { params: Promise<{ id: string }> }) {
  const params = await props.params;
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: 'Authentication required' },
        { status: 401 }
      );
    }

    const { id } = params;

    // Get conversation with photos
    const conversation = await prisma.conversation.findUnique({
      where: { id },
      include: {
        Project: true,
        User: true,
      },
    });

    if (!conversation) {
      return NextResponse.json(
        { error: 'Conversation not found' },
        { status: 404 }
      );
    }

    // Verify ownership or admin access
    if (
      conversation.userId !== session.user.id &&
      session.user.role !== 'admin'
    ) {
      return NextResponse.json(
        { error: 'Access denied' },
        { status: 403 }
      );
    }

    // Verify this is a daily report chat
    if (conversation.conversationType !== 'daily_report') {
      return NextResponse.json(
        { error: 'Only daily report chats support photo exports' },
        { status: 400 }
      );
    }

    const photos = (conversation.photos as unknown as PhotoMetadata[]) || [];

    if (photos.length === 0) {
      return NextResponse.json({
        photos: [],
        message: 'No photos to export',
      });
    }

    // Generate signed URLs for all photos (valid for 1 hour)
    const s3Client = createS3Client();
    const { bucketName } = getBucketConfig();

    const photosWithUrls = await Promise.all(
      photos.map(async (photo) => {
        try {
          const signedUrl = await getSignedUrl(
            s3Client,
            new GetObjectCommand({
              Bucket: bucketName,
              Key: photo.cloud_storage_path,
            }),
            { expiresIn: 3600 } // 1 hour
          );

          return {
            ...photo,
            signedUrl,
          };
        } catch (error) {
          logger.error('Error generating signed URL for photo', error, { photoId: photo.id });
          return {
            ...photo,
            signedUrl: null,
            error: 'Failed to generate URL',
          };
        }
      })
    );

    // Prepare export metadata
    const exportData = {
      reportInfo: {
        title: conversation.title,
        date: conversation.dailyReportDate || conversation.createdAt,
        project: conversation.Project?.name || 'Unknown Project',
        createdBy: conversation.User?.email || 'Unknown',
      },
      photos: photosWithUrls,
      photoCount: photos.length,
      summary: {
        totalPhotos: photos.length,
        byTrade: getPhotosByTrade(photos),
        byLocation: getPhotosByLocation(photos),
        withCaptions: photos.filter((p) => p.captionSource === 'auto' || p.captionSource === 'user').length,
        autoGenerated: photos.filter((p) => p.captionSource === 'auto').length,
      },
      exportedAt: new Date().toISOString(),
    };

    return NextResponse.json(exportData);
  } catch (error) {
    logger.error('Error exporting photos', error);
    return NextResponse.json(
      { error: 'Failed to export photos' },
      { status: 500 }
    );
  }
}

/**
 * Group photos by trade
 */
function getPhotosByTrade(photos: PhotoMetadata[]): Record<string, number> {
  const byTrade: Record<string, number> = {};
  
  photos.forEach((photo) => {
    if (photo.trade) {
      byTrade[photo.trade] = (byTrade[photo.trade] || 0) + 1;
    }
  });
  
  return byTrade;
}

/**
 * Group photos by location
 */
function getPhotosByLocation(photos: PhotoMetadata[]): Record<string, number> {
  const byLocation: Record<string, number> = {};
  
  photos.forEach((photo) => {
    if (photo.location) {
      byLocation[photo.location] = (byLocation[photo.location] || 0) + 1;
    }
  });
  
  return byLocation;
}
